#!/usr/bin/env bash
# Configure your domain zone so that the
# subdomain www points to your load-balancer IP (lb-01). 

info_dom_and_subdom () {
        output=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $4}')
        aux_output=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $5}')
        echo "The subdomain $2 is a $output record and points to $aux_output"
        return 0
}
# When input IP addres
if [ -z "$2" ]
then
    info_dom_and_subdom "$1" "www"
    info_dom_and_subdom "$1" "lb-01"
    info_dom_and_subdom "$1" "web-01"
    info_dom_and_subdom "$1" "web-02"
else
    info_dom_and_subdom "$1" "$2"
fi
:()