#!/usr/bin/env bash
#Install nginx on your web-01 server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://twitter.com/andres0191/ permanent;' /etc/nginx/sites-available/default
sudo service nginx start