#!/usr/bin/env bash
sudo add-apt-repository ppa: vbernat / haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i "$ a frontend local_configuration\n \tbind *:80\n \tmode http\n \tdefault_backend local_configuration"
sudo sed -i "$ a backend local_configuration\n \tmode http\n \tbalance rundrobin\n \toption forwardfor\n \thttp-request set-header X-Forwarded-Port %[dst_port]\n \thttp-request add-header X-Forwarded-Proto https if { ssl_fc }\n \toption httpchk HEAD / \n \tHTTP/1.1\r\nHost:localhost\n \t1141-web-01 34.73.62.124:80 check\n \t1141-web-02 34.202.231.173:80 check\n"
sudo service haproxy restart
