#!/usr/bin/env bash
#install haproxy
sudo add-apt-repository ppa:vbernat /haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i "$ a frontend local_configuration\n \tbind *:80\n \tmode http\n \tdefault_backend local_configuration\n" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a backend local_configuration\n \tmode http\n \tbalance roundrobin\n \tserver 1141-web-01 34.73.62.124:80 check\n \tserver 1141-web-02 34.202.231.173:80 check\n" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
