#!/usr/bin/env bash
sed -i "s/listen * default_server;/listen 80 default_server;/g" /etc/nginx/sites-available/default
sed -i "s/listen * default_server;/listen 80 default_server;/g" /etc/nginx/sites-enabled/default
