#!/usr/bin/env bash
sudo sed -i "s/listen * default_server;/listen 80 default_server;/g" /etc/nginx/sites-available/default
sudo sed -i "s/listen * default_server;/listen 80 default_server;/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
