#!/usr/bin/env bash
sed -i "s/listen * default_server;/listen 80 default_server;/g" /etc/nginx/sites-enabled/default
sed -i "s/listen * default_server ipv60nly=on;/s/listen [::]80 default_server ipv60nly=on;/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
