#!/usr/bin/env bash
#displays Holberton School 10 times, but for the 9th iteration, print Hi
count=0
while [ $count -lt 10 ]
do
    printf "Holberton School\n"
    if [ $count == 8 ]
        then
        printf "Hi\n"
    fi
    let count=count+1
done
