#!/usr/bin/env bash
count=0
while [ $count -lt 10 ]
do
    if [ $count == 3 ]
        then
        printf "bad luck\n"
    elif [ $count == 7 ]
        then
        printf "good luck\n"
    else
        printf "Holberton School\n"
    fi
    let count=count+1
done