#!/usr/bin/env bash
#script that loops from 1 to 10 and print bad luck in the 4to loop, good luck in the 8th loop
count=0
while [ $count -lt 10 ]
do
    if [ $count == 3 ]
        then
        printf "bad luck\n"
    elif [ $count == 7 ]
        then
        printf "good luck\n"
    else
        printf "Holberton School\n"
    fi
    let count=count+1
done
