#!/usr/bin/env bash
hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minute=1
    while [ $minute -le 59 ]
    do
        printf "%d\n" "$minute"
        let minute=minute+1
    done
    let hour=hour+1
done
