#!/bin/bash/env bash
# Fix this container so that Nginx is running as the nginx user.
pkill -f apache2
chown -R nginx:nginx /etc/nginx
chown -R nginx:nginx /usr/share/nginx
chmod 755 -R /etc/nginx
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen \[::\]:8080 default_server ipv6only=on;/' /etc/nginx/sites-available/default
sed -i 's+pid /run/nginx.pid;+pid /tmp/nginx.pid;+' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
