#!/bin/bash/env bash
# Fix this container so that Nginx is running as the nginx user.
pkill -f apache2
chown -R nginx:nginx /etc/nginx
chown -R nginx: nginx /usr/share/nginx
chmod 744 /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sed -i 's+pid /run/nginx.pid;+pid /tmp/nginx.pid;+' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
